###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
# Crear un nuevo producto
POST http://localhost:3000/products
Content-Type: application/json

{
    "product": "Bicicleta",
    "description": "Bicicleta de montaña",
    "stock": 5,
    "price": 1000,
    "disount": 10.00

}    

###
# Editar un producto existente
PUT http://localhost:3000/products/1
Content-Type: application/json

{
    "product": "Bicicleta",
    "description": "Bicicleta de montaña",
    "stock": 5,
    "price": 1000,
    "disount": 13.00
}

###
# Eliminar un producto
DELETE http://localhost:3000/products/2
