GET http://localhost:3000/pokemons

###
GET http://localhost:3000/pokemons/play

###
GET http://localhost:3000/pokemons/1

###
POST http://localhost:3000/pokemons
Content-Type: application/json

{
    "name": "charmander",
    "image": "charmander.png"
    
}

###
PUT http://localhost:3000/pokemons/153
Content-Type: application/json

{
    "name": "mewtwo",
    "image": "mewtwo.png"
}

###
DELETE  http://localhost:3000/pokemons/152